# Site Info
title: Michelle's Blog
tagline: 'for some various ideas'
description: 'blog for data science, music review, and daily ideas.'
url: http://michelle1223.github.io
logo: '/public/logo.png'
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author:
  name: Michelle Min
  description: Just loving the things I love, as always!
  gravatar: d7fe7ba42d1d13c7dfa1b3f447eb4f12 # md5 hash of your email address
  contact:
    #linkedin:  https://www.linkedin.com/in/gichanglee/
    github:    https://github.com/michelle1223
    instagram: https://www.instagram.com/4min.ofyourday
    #facebook:  https://www.facebook.com/gichanglee.84
    #twitter:  <hide>
    #weibo:    <hide>
    email:     mailto:acoustic1223@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Contents:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: https://michelle1223.github.io/public/img/picture.JPG
  caption: Photography by Michelle Min. May, 2019

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: 'michelle1223' # leave blank if you don't want disqus
